### ISSUE TITLE
MSGraph SDK 5.48: Kiota.Abstractions calling Std.UriTemplate version 1.0.0.0

### ISSUE THREAD

**Issue by MAlabaster** [microsoftgraph/msgraph-sdk-dotnet#2441]
### Describe the bug

Reading user mailboxes obtaining root folder using MSGraph. 
Since update to Nuget Packages, throws an error saying Could not load file or assembly 'Std.UriTemplate, Version=1.0.0.0. 
Latest version availableStd.UriTemplate is 0.0.0.56

### Expected behavior

To load assembly version 0.0.0.56

### How to reproduce

create MSgraph client, authenticate with client credentials 
get root mail folder

```
MSGRootFolder = await graphClient
     .Users[theTargetAccount]
     .MailFolders["msgfolderroot"]
     .GetAsync();
```

### SDK Version

5.48.0

### Latest version known to work for scenario above?

unknown 

### Known Workarounds

edit app.config bindingRedirect <bindingRedirect oldVersion="0.0.0.0-1.0.0.0" newVersion="0.0.56.0" />

### Debug output

<details><summary>Click to expand log</summary>
```

System.IO.FileLoadException: Could not load file or assembly 'Std.UriTemplate, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c118b0afb4598f9a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Std.UriTemplate, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c118b0afb4598f9a'
   at Microsoft.Kiota.Abstractions.RequestInformation.get_URI()
   at Microsoft.Kiota.Abstractions.Authentication.BaseBearerTokenAuthenticationProvider.<AuthenticateRequestAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<GetHttpResponseMessage>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Users.Item.MailFolders.Item.MailFolderItemRequestBuilder.<GetAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at miImportMgmtConsole.frmProfileSettings.<btnConnect_Click>d__38.MoveNext() in C:\Users\Martin\source\repos\miImportSolution\miImportMgmtConsoleNew\frmProfileSettings.cs:line 331

=== Pre-bind state information ===
LOG: DisplayName = Std.UriTemplate, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c118b0afb4598f9a
 (Fully-specified)
LOG: Appbase = file:///C:/Users/Martin/source/repos/miImportSolution/miImportMgmtConsoleNew/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.Kiota.Abstractions, Version=1.8.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\Martin\source\repos\miImportSolution\miImportMgmtConsoleNew\bin\Debug\miImportMgmtConsole.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Std.UriTemplate, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c118b0afb4598f9a
LOG: Attempting download of new URL file:///C:/Users/Martin/source/repos/miImportSolution/miImportMgmtConsoleNew/bin/Debug/Std.UriTemplate.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

---------------------------
OK   
---------------------------


```
</details>

### Configuration

Win 10, 2012, 2022 x64

**Comment by andrueastman** [comment]
Thanks for raising this @MAlabaster 

Just to confirm, were performing an upgrade from a previous SDK version to the current one? Are you able to share a small repro project to help investigate?

**Comment by donjarducius** [comment]
I have now addressed this error as well. The solution is to downgrade nuget from 0.0.56.0 to 0.0.55.0 as required by Microsoft.Kiota.Abstractions. If the version of Std.UriTemplate is higher, the program will crash with a message that Std.UriTemplate version 1.0.0 is missing

**Comment by MAlabaster** [comment]
It’s a great big solution but I have a utility for finding emails that I can try and upgrade from and get the same problem, if you can wait for next week I’ll send you a copy. I’e overcome it with binding redirect but I still get the conflict messages on the build.

**Comment by MAlabaster** [comment]
Hi Don,
By “downgrade nuget from 0.0.56.0 to 0.0.55.0”  Do you mean downgrade   Std.UriTemplate nuget package? Is Kiota.Abstractions 1.8.1 OK with that?
I just used binding redirect oldversion = 0.0.0.0-1.0.0.0 still get the conflict warnings though.
Martin

**Comment by donjarducius** [comment]
Yes, downgrade Std.UriTemplate to version 0.0.55.0.
Microsoft.Kiota.Abstractions can remain in version 1.8.1, in my opinion there is no problem with MSGraph, nor with Microsoft.Kiota.Abstractions.
The problem is with version substitution when compiling a project that contains Microsoft.Kiota.Abstractions (in 1.8.1) and Std.UriTemplate (in 0.0.56), where instead of replacing version 0.0.55.0 with version 0.0.56.0, version 1.0.0.0 is requested incorrectly.

The version substitution bug took me half an hour of work today and finally using in my .Net Framework 4.8 project I have MSGraph version 5.49.0, Microsoft.Kiota.Abstractions version 1.8.1 and Std.UriTemplate 0.0.55.0 and everything is working.

**Comment by andrueastman** [comment]
An update to the Microsoft.Kiota.Abstractions has been released that references Std.UriTemplate to version 0.0.56.0. Any chance you can confirm if this is still an issue?

@MAlabaster @MAlabaster

**Comment by donjarducius** [comment]
Now it is ok, the problem is not manifested. However, it would be good to find out why the version redirection misdetermines the target version.

**Comment by andrueastman** [comment]
There's the possibility it may have something to do with https://github.com/std-uritemplate/std-uritemplate/issues/154 where the library did not properly specify a FileVersion property (which it now does). Hopefully the latest release should help with the resolution issue.

**Comment by MAlabaster** [comment]
It has fixed it,  1.8.3, when I update it the conflict messages go away and the MSGraph call to get the root email folders is working
There’s also a new version of Graph and Kiota.Http.Http libraries but I’m drawing breath before I update those

**Comment by MAlabaster** [comment]
It does, thank you all.

**Comment by MAlabaster** [comment]
Thanks, now of course superseded by MKA v1.8.3

**Comment by andrueastman** [comment]
We'll close this for now @MAlabaster @donjarducius given the latest changes and re-open in the event of any re-occurrences.

**Comment by lbermes** [comment]
Seems to be back with 1.8.4

**Comment by donjarducius** [comment]
No it is not, I have now tried version 1.8.4 and everything is ok.

**Comment by lbermes** [comment]
You are right, i have it already when upgrading from 1.8.1 ot 1.8.3
I have all (also graph) on latest revision except kiota:
This here works
    <PackageReference Include="Microsoft.Kiota.Abstractions">
      <Version>1.8.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Kiota.Http.HttpClientLibrary">
      <Version>1.3.9</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Kiota.Serialization.Form">
      <Version>1.1.5</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Kiota.Serialization.Json">
      <Version>1.2.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Kiota.Serialization.Multipart">
      <Version>1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Kiota.Serialization.Text">
      <Version>1.1.4</Version>
    </PackageReference>


When I switch to 1.8.3 without mapping it in app.config I get the message with 
There was a conflict between "Std.UriTemplate, Version=0.0.56.0, Culture=neutral, PublicKeyToken=c118b0afb4598f9a" and "Std.UriTemplate, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c118b0afb4598f9a".

I change the app.config to 1.8.3 and it is ok

Now I update Microsoft.Kiota.Http.HttpClientLibrary to 1.3.10 and even with the adjusted app config I get always the conflict.
Even when I update all to the latest revision and set the app.config I get the conflict.

**Comment by lbermes** [comment]
oops, it removed the markup:
Microsoft.Kiota.Abstractions
      1.8.1

Microsoft.Kiota.Http.HttpClientLibrary
      1.3.9

Microsoft.Kiota.Serialization.Form
      1.1.5

Microsoft.Kiota.Serialization.Json
      1.2.0

Microsoft.Kiota.Serialization.Multipart
      1.1.3

Microsoft.Kiota.Serialization.Text
      1.1.4

**Comment by donjarducius** [comment]
The problem is with the version redirection of Std.UriTemplate, where it is incorrectly redirected to version 1.0.0.0 (by file version, not library version).
If you are using Microsoft.Kiota.Abstractions version 1.8.1, you must have Std.UriTemplate version 0.0.55.0.
For Microsoft.Kiota.Abstractions 1.8.2 and 1.8.3, use Std.UriTemplate version 0.0.56.0.
For Microsoft.Kiota.Abstractions 1.8.4, use Std.UriTemplate 0.0.57.0.

MSGraph SDK or Kiota.Abstractions are not responsible for this error, the error is in the versioning of the Std.UriTemplate library. As long as the version of Std.UriTemplate is less than 1.0.0.1 this error will manifest itself.



Translated with DeepL.com (free version)

**Comment by lbermes** [comment]
Yes, this was probably not the right place to discuss it but thanks for your adivce adding the Std.UriTemplate to the app.config solved it for me.
